### ISSUE TITLE
Add API to Read the Docs

### ISSUE THREAD

**Issue by aweinstein** [gsp-eeg/EEGraSP#179]
EEGraSP [Read the Docs](https://eegrasp.readthedocs.io/en/latest/) only has an Examples section. Add the API and References section (and possibly the Changelog and Contributing section; see [pyGSP2 Read the Docs](https://pygsp2.readthedocs.io/en/latest/index.html) as an example).

**Comment by lcortesg** [comment]
Working version, waiting for merge [https://eegrasp.readthedocs.io/en/179-add-api-to-read-the-docs/index.html](https://eegrasp.readthedocs.io/en/179-add-api-to-read-the-docs/index.html)
