### ISSUE TITLE
Publish release in PyPi

### ISSUE THREAD

**Issue by lcortesg** [gsp-eeg/EEGraSP#49]

**Comment by lcortesg** [comment]
[Released](https://pypi.org/project/EEGraSP/)

**Comment by aweinstein** [comment]
@lcortesg, please update the README with the corresponding installation instructions through PyPi.

**Comment by lcortesg** [comment]
@aweinstein What's your username in PyPi? its needed for the invitation for both the EEGraSP package and the PyGSP2 package!
