### ISSUE TITLE
EEGrasp should take an NME class as attribute.

### ISSUE THREAD

**Issue by aweinstein** [gsp-eeg/EEGraSP#55]
The current implementation of class [`EEGrasp`](https://github.com/gsp-eeg/eegrasp/blob/1b0c40918bcebce0e5d87f7675022f34c2d3dc2f/eegrasp/eegrasp.py#L10C7-L10C14) has attributes `data` `coordinates`, and `labels`. Instead, the class attribute should be an MNE object.

We need to discuss whether the class can use either a raw or an embedded object, whether we use different classes for each object, etc.

**Comment by julioRodino** [comment]
I've added an option to detect if an mne object is passed when the EEGrasp class is initialized. When using `gsp = EEGrasp(mne_object)`, the initialization of the class detects if the `mne_object` contains the `.get_data` and `.info` attributes. Then, it will extract them and assign them as attributes of the class instance. 

I think this is a nice layer of compatibility to make it easy to transition between mne and eegrasp functionality. Though I would only apply this to the initialization of the class. For other methods, for example, `EEGrasp.compute_distance` I think we should maintain it as it is: you can use it by passing an array with coordinates or by passing None and it will use `self.coordinates` to compute the distance matrix.
