### ISSUE TITLE
Badges are broken

### ISSUE THREAD

**Issue by aweinstein** [gsp-eeg/EEGraSP#91]
Several of the badges are broken:

![image](https://github.com/user-attachments/assets/e1aff384-03fd-45c6-972b-8b076eb72a3a)

**Comment by aweinstein** [comment]
@lcortesg Can you make the v0.0.4 realease?

**Comment by lcortesg** [comment]
@aweinstein Yes! but first I would need the changes of [PR#93](https://github.com/gsp-eeg/EEGraSP/pull/93) merged into main to do it via CI
